spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roty?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 233b442d79cbe21409405bd3e8e1fc7c
            client-secret: d9MPecFGz6wu2UA8jZMy008OjNewDXVt
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth/kakao.com/oauth/token
            user-info-uri: https://kapi.kako.com/v2/user/me
            user-name-attribute: id





